import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavbarPublic from "./components/public/NavbarPublic";
import { cookies } from "next/headers";
import NavigationWrapper from "./components/NavigationWrapper";
// import { useAuthStore } from "@/stores/authStore";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const user = useAuthStore((state) => state.user)
  const userCookie = await cookies();
  const userSession = userCookie.has("session_token");
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className=" ">
          <NavigationWrapper />
          {children}
        </main>
      </body>
    </html>
  );
}
